# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lt-note
email: 3924712@qq.com
description: > # this means to ignore newlines until "baseurl:"
  My note, record some useful knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lt-beg

# Build settings
markdown: kramdown

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
